title: "Hawker Dashboard"
subtitle: ""
logo: "logo.svg"

header: true # set to false to hide header
footer: <p>Created with <span class="has-text-danger">❤️</span></p> # set false if you want to hide it.

theme: default # 'default' or theme provided in assets/themes

links:
  -

services:
  - name: "Applications"
    icon: ""
    items:
      - name: "Plex Server"
        logo: ""
        subtitle: "Media Server"
        tag: "app"
        url: "http://127.0.0.1:32400/web/index.html#!/"
